# Generated by Django 5.1 on 2024-09-30 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_destination_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_destinations', to=settings.AUTH_USER_MODEL),
        ),
    ]
