# Generated by Django 5.1 on 2024-11-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_destination_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activity_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_adults', models.IntegerField(default=1)),
                ('number_of_infants', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.destination')),
            ],
        ),
    ]
