# Generated by Django 4.2 on 2025-06-01 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_calculator', '0002_alter_budgetcalculator_accommodation_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcalculator',
            name='number_of_adults',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
